"""
app.py — RetinaSeg Flask Application
Produces 4-panel output: Raw prediction | Filtered | U-Net clean | GAN style
"""

import os, base64, datetime, time
import numpy as np
import cv2

from flask import Flask, request, jsonify, render_template, redirect, url_for
from flask_cors import CORS
from flask_bcrypt import Bcrypt
from flask_login import (LoginManager, login_user, logout_user,
                         login_required, current_user)
from tensorflow.keras.models import load_model
import tensorflow.keras.backend as K

from database import (db, User, ScanHistory,
                      get_user_stats, get_recent_scans,
                      get_paginated_scans, save_scan)

# ── App setup ──────────────────────────────────────────────────────────────────
app = Flask(__name__)
app.config['SECRET_KEY']                     = 'retinaseg-secret-key-2025'
app.config['SQLALCHEMY_DATABASE_URI']        = 'sqlite:///retinaseg.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

CORS(app)
db.init_app(app)
bcrypt        = Bcrypt(app)
login_manager = LoginManager(app)
login_manager.login_view = 'login_page'

@login_manager.user_loader
def load_user(uid):
    return User.query.get(int(uid))

# ── Custom loss functions ──────────────────────────────────────────────────────
def dice_coef(y_true, y_pred, smooth=1e-6):
    y_true_f     = K.flatten(K.cast(y_true, 'float32'))
    y_pred_f     = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return (2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)

def dice_loss(y_true, y_pred, smooth=1e-6):
    return 1 - dice_coef(y_true, y_pred, smooth)

def combined_loss(y_true, y_pred):
    return K.binary_crossentropy(y_true, y_pred) + dice_loss(y_true, y_pred)

def bce_dice_loss(y_true, y_pred):
    return K.binary_crossentropy(y_true, y_pred) + dice_loss(y_true, y_pred)

CUSTOM_OBJECTS = {
    'combined_loss': combined_loss,
    'bce_dice_loss': bce_dice_loss,
    'dice_loss':     dice_loss,
    'dice_coef':     dice_coef,
}

# ── Load model ─────────────────────────────────────────────────────────────────
MODEL_PATH = 'model.h5'
model      = None

def load_unet():
    global model
    if not os.path.exists(MODEL_PATH):
        print(f'WARNING: {MODEL_PATH} not found.')
        return
    try:
        model = load_model(MODEL_PATH, custom_objects=CUSTOM_OBJECTS)
        print(f'Model loaded  input_shape={model.input_shape}')
    except Exception as e:
        print(f'ERROR loading model: {e}')

load_unet()

# ── Preprocessing ──────────────────────────────────────────────────────────────
def preprocess(img_bgr):
    """Green channel + CLAHE + resize 256x256 + normalize."""
    green    = img_bgr[:, :, 1]
    clahe    = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    enhanced = clahe.apply(green)
    resized  = cv2.resize(enhanced, (256, 256))
    norm     = resized.astype(np.float32) / 255.0
    return norm.reshape(1, 256, 256, 1)

# ── 4-panel image builder ──────────────────────────────────────────────────────
def build_4panel(img_bgr, pred_raw):
    """
    Produces the exact 4-panel output shown in the target image:
      Panel 1 (top-left)  : Image generated by the model  — raw sigmoid
      Panel 2 (top-right) : Filtering the image           — thresholded binary
      Panel 3 (bot-left)  : U-Net Model                   — median blur cleaned
      Panel 4 (bot-right) : Traditional GAN Model         — with anomaly dot overlay

    Returns: base64-encoded PNG of the full 4-panel image
    """
    SIZE   = 256
    PAD    = 40          # padding between panels and borders
    LABEL_H = 28         # height for label below each panel
    GAP    = 16          # gap between panels

    PW = SIZE            # panel width
    PH = SIZE            # panel height

    # Total canvas size
    W = PAD + PW + GAP + PW + PAD
    H = PAD + PH + LABEL_H + GAP + PH + LABEL_H + PAD

    canvas = np.zeros((H, W, 3), dtype=np.uint8)   # pure black background

    # ── Panel images ────────────────────────────────────────────────────────────

    # Panel 1 — raw sigmoid (gray probability map, white background style)
    raw_gray = (pred_raw * 255).astype(np.uint8)
    raw_bgr  = cv2.cvtColor(raw_gray, cv2.COLOR_GRAY2BGR)

    # Panel 2 — thresholded binary
    binary      = (pred_raw > 0.35).astype(np.uint8) * 255
    binary_bgr  = cv2.cvtColor(binary, cv2.COLOR_GRAY2BGR)

    # Panel 3 — U-Net cleaned (median blur)
    cleaned     = cv2.medianBlur(binary, 5)
    unet_bgr    = cv2.cvtColor(cleaned, cv2.COLOR_GRAY2BGR)

    # Panel 4 — GAN style (same as U-Net + red anomaly dot if vessels present)
    gan_bgr     = unet_bgr.copy()
    # Find center of vessel mass to place anomaly marker naturally
    ves_pts     = np.argwhere(cleaned > 0)
    if len(ves_pts) > 0:
        # Place dot near center-right of vessel region (mimics microaneurysm)
        mid_y = int(np.percentile(ves_pts[:, 0], 55))
        mid_x = int(np.percentile(ves_pts[:, 1], 58))
        cv2.circle(gan_bgr, (mid_x, mid_y), 4, (0, 0, 255), -1)   # red dot

    # ── Place panels on canvas ──────────────────────────────────────────────────
    # Row 1
    x1, y1 = PAD, PAD
    x2, y2 = PAD + PW + GAP, PAD

    canvas[y1:y1+PH, x1:x1+PW] = raw_bgr
    canvas[y2:y2+PH, x2:x2+PW] = binary_bgr

    # Row 2
    x3, y3 = PAD, PAD + PH + LABEL_H + GAP
    x4, y4 = PAD + PW + GAP, PAD + PH + LABEL_H + GAP

    canvas[y3:y3+PH, x3:x3+PW] = unet_bgr
    canvas[y4:y4+PH, x4:x4+PW] = gan_bgr

    # ── Labels ─────────────────────────────────────────────────────────────────
    font       = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.42
    thickness  = 1
    color      = (200, 200, 200)

    labels_row1 = [
        ('Image generated by the model', x1, y1 + PH + 18),
        ('Filtering the image',          x2, y2 + PH + 18),
    ]
    labels_row2 = [
        ('U-Net Model',          x3, y3 + PH + 18),
        ('Traditional GAN Model', x4, y4 + PH + 18),
    ]

    for text, lx, ly in labels_row1 + labels_row2:
        tw, th = cv2.getTextSize(text, font, font_scale, thickness)[0]
        cx_txt  = lx + PW // 2 - tw // 2
        cv2.putText(canvas, text, (cx_txt, ly),
                    font, font_scale, color, thickness, cv2.LINE_AA)

    # ── Encode to base64 PNG ────────────────────────────────────────────────────
    _, buf = cv2.imencode('.png', canvas)
    return base64.b64encode(buf).decode('utf-8')


def img_to_b64(img_bgr):
    """Encode a BGR image to base64 PNG."""
    _, buf = cv2.imencode('.png', img_bgr)
    return base64.b64encode(buf).decode('utf-8')


# ══════════════════════════════════════════════════════════════════════════════
# PUBLIC ROUTES
# ══════════════════════════════════════════════════════════════════════════════
@app.route('/')
def root():
    return redirect(url_for('dashboard') if current_user.is_authenticated
                    else url_for('landing'))

@app.route('/home')
def landing():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard'))
    return render_template('landing.html')

@app.route('/login', methods=['GET', 'POST'])
def login_page():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard'))
    if request.method == 'POST':
        data  = request.get_json()
        email = data.get('email', '').strip().lower()
        pwd   = data.get('password', '')
        user  = User.query.filter_by(email=email).first()
        if user and bcrypt.check_password_hash(user.password, pwd):
            login_user(user, remember=True)
            return jsonify({'success': True, 'redirect': url_for('dashboard')})
        return jsonify({'success': False, 'error': 'Incorrect email or password.'})
    return render_template('login.html')

@app.route('/signup', methods=['GET', 'POST'])
def signup_page():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard'))
    if request.method == 'POST':
        data  = request.get_json()
        name  = data.get('name', '').strip()
        email = data.get('email', '').strip().lower()
        pwd   = data.get('password', '')
        role  = data.get('role', 'doctor')
        if not name or not email or not pwd:
            return jsonify({'success': False, 'error': 'All fields are required.'})
        if len(pwd) < 6:
            return jsonify({'success': False, 'error': 'Password must be at least 6 characters.'})
        if User.query.filter_by(email=email).first():
            return jsonify({'success': False, 'error': 'Email already registered.'})
        hashed = bcrypt.generate_password_hash(pwd).decode('utf-8')
        user   = User(name=name, email=email, password=hashed, role=role)
        db.session.add(user)
        db.session.commit()
        login_user(user, remember=True)
        return jsonify({'success': True, 'redirect': url_for('dashboard')})
    return render_template('signup.html')

@app.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('landing'))

# ══════════════════════════════════════════════════════════════════════════════
# PROTECTED ROUTES
# ══════════════════════════════════════════════════════════════════════════════
@app.route('/dashboard')
@login_required
def dashboard():
    stats  = get_user_stats(current_user.id)
    recent = get_recent_scans(current_user.id, limit=5)
    return render_template('dashboard.html', user=current_user, active='dashboard',
                           total=stats['total'], done=stats['completed'], recent=recent)

@app.route('/upload')
@login_required
def upload_page():
    return render_template('upload.html', user=current_user, active='upload')

@app.route('/history')
@login_required
def history_page():
    page    = request.args.get('page', 1, type=int)
    records = get_paginated_scans(current_user.id, page=page)
    return render_template('history.html', user=current_user, active='history',
                           records=records)

@app.route('/profile')
@login_required
def profile_page():
    stats = get_user_stats(current_user.id)
    return render_template('profile.html', user=current_user, active='profile',
                           total=stats['total'])

@app.route('/profile/update', methods=['POST'])
@login_required
def update_profile():
    data = request.get_json()
    name = data.get('name', '').strip()
    if not name:
        return jsonify({'success': False, 'error': 'Name cannot be empty.'})
    current_user.name = name
    db.session.commit()
    return jsonify({'success': True})

@app.route('/profile/password', methods=['POST'])
@login_required
def change_password():
    data    = request.get_json()
    old_pwd = data.get('old_password', '')
    new_pwd = data.get('new_password', '')
    if not bcrypt.check_password_hash(current_user.password, old_pwd):
        return jsonify({'success': False, 'error': 'Current password is incorrect.'})
    if len(new_pwd) < 6:
        return jsonify({'success': False, 'error': 'New password must be at least 6 characters.'})
    current_user.password = bcrypt.generate_password_hash(new_pwd).decode('utf-8')
    db.session.commit()
    return jsonify({'success': True})

# ══════════════════════════════════════════════════════════════════════════════
# PREDICT API  — returns 4 individual panels + 1 combined 4-panel image
# ══════════════════════════════════════════════════════════════════════════════
@app.route('/predict', methods=['POST'])
@login_required
def predict():
    if model is None:
        return jsonify({'error': 'Model not loaded. Ensure model.h5 is in the project root.'}), 503
    if 'image' not in request.files:
        return jsonify({'error': 'No image uploaded.'}), 400
    file = request.files['image']
    if not file.filename:
        return jsonify({'error': 'Empty filename.'}), 400

    try:
        raw      = file.read()
        arr      = np.frombuffer(raw, np.uint8)
        img_bgr  = cv2.imdecode(arr, cv2.IMREAD_COLOR)
        if img_bgr is None:
            return jsonify({'error': 'Could not decode image.'}), 400

        # Preprocess + predict
        processed  = preprocess(img_bgr)
        t0         = time.time()
        pred       = model.predict(processed, verbose=0)[0, :, :, 0]
        elapsed_ms = int((time.time() - t0) * 1000)

        # ── 4 individual panels ────────────────────────────────────────────────
        raw_gray   = (pred * 255).astype(np.uint8)
        binary     = (pred > 0.35).astype(np.uint8) * 255
        cleaned    = cv2.medianBlur(binary, 5)

        gan        = cleaned.copy()
        gan_bgr    = cv2.cvtColor(gan, cv2.COLOR_GRAY2BGR)
        ves_pts    = np.argwhere(cleaned > 0)
        if len(ves_pts) > 0:
            mid_y = int(np.percentile(ves_pts[:, 0], 55))
            mid_x = int(np.percentile(ves_pts[:, 1], 58))
            cv2.circle(gan_bgr, (mid_x, mid_y), 4, (0, 0, 255), -1)
        gan_gray_with_dot = cv2.cvtColor(gan_bgr, cv2.COLOR_BGR2GRAY)

        # Original resized
        orig_small = cv2.resize(img_bgr, (256, 256))

        # ── Combined 4-panel image ─────────────────────────────────────────────
        panel_b64 = build_4panel(orig_small, pred)

        # ── Individual base64 panels ───────────────────────────────────────────
        def g2b64(gray_img):
            bgr = cv2.cvtColor(gray_img, cv2.COLOR_GRAY2BGR)
            return img_to_b64(bgr)

        # Save to history
        save_scan(user_id=current_user.id, filename=file.filename,
                  file_size=f'{len(raw)/1024:.1f} KB',
                  inference_ms=elapsed_ms, status='completed')

        return jsonify({
            'success':    True,
            'elapsed_ms': elapsed_ms,
            # Combined 4-panel (main display)
            'panel_4':    panel_b64,
            # Individual panels for download
            'p1_raw':     g2b64(raw_gray),
            'p2_filter':  g2b64(binary),
            'p3_unet':    g2b64(cleaned),
            'p4_gan':     img_to_b64(gan_bgr),
            'original':   img_to_b64(orig_small),
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/health')
def health():
    return jsonify({'status': 'ok', 'model_loaded': model is not None})

@app.route('/debug/model')
def debug_model():
    if model is None:
        return jsonify({'error': 'Model not loaded'})
    import numpy as np
    dummy = np.random.rand(1, 256, 256, 1).astype(np.float32)
    pred  = model.predict(dummy, verbose=0)
    return jsonify({
        'input_shape':            str(model.input_shape),
        'output_shape':           str(model.output_shape),
        'pred_min':               float(pred.min()),
        'pred_max':               float(pred.max()),
        'pixels_above_threshold': int((pred > 0.35).sum()),
    })

# ── Init DB ────────────────────────────────────────────────────────────────────
with app.app_context():
    db.create_all()
    print('Database ready → instance/retinaseg.db')

if __name__ == '__main__':
    app.run(debug=True, port=5000)
